In [2]:
import torch 

In [3]:
x=torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.empty()和torch.zeros()的主要区别在于它们初始化张量元素的方式，torch.empty()未初始化张量，torch.zeros()将张量的元素初始化为0。

In [4]:
x = torch.rand(5,3)
x

tensor([[0.8142, 0.0103, 0.1324],
        [0.2860, 0.3174, 0.9101],
        [0.0358, 0.9176, 0.5675],
        [0.0217, 0.4247, 0.4713],
        [0.0297, 0.5149, 0.0412]])

In [5]:
#用new_方法创建对象
x = x.new_ones(5,3,dtype=torch.double )#64 双精度
print(x)
x = torch.randn_like (x,dtype=torch.float)# 32 双精度
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6338, -1.6565, -0.9811],
        [-1.3722, -0.1331,  1.2598],
        [-0.7445,  0.2115,  0.0526],
        [-0.9367,  0.2224,  1.3718],
        [ 1.7385, -0.1596,  0.7639]])


In [6]:
x.size()

torch.Size([5, 3])

加法运算 


加法1

In [7]:
y = torch.rand(5,3)
print(x+y)

tensor([[-0.2243, -1.5971, -0.6673],
        [-0.8673,  0.2088,  2.2556],
        [-0.5025,  0.8107,  0.9395],
        [-0.1228,  0.4929,  1.5021],
        [ 1.9190,  0.1930,  1.3798]])


加法2

In [8]:
print(torch.add(x,y))

tensor([[-0.2243, -1.5971, -0.6673],
        [-0.8673,  0.2088,  2.2556],
        [-0.5025,  0.8107,  0.9395],
        [-0.1228,  0.4929,  1.5021],
        [ 1.9190,  0.1930,  1.3798]])


将 结果存储在 预设的tensor 中

In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out= result)# 将结果存储在 out= 后面的变量中
print(result)

tensor([[-0.2243, -1.5971, -0.6673],
        [-0.8673,  0.2088,  2.2556],
        [-0.5025,  0.8107,  0.9395],
        [-0.1228,  0.4929,  1.5021],
        [ 1.9190,  0.1930,  1.3798]])


In [10]:
y.add_(x) # 把x 加上 y ，并且把值放在y里面
print(y)


tensor([[-0.2243, -1.5971, -0.6673],
        [-0.8673,  0.2088,  2.2556],
        [-0.5025,  0.8107,  0.9395],
        [-0.1228,  0.4929,  1.5021],
        [ 1.9190,  0.1930,  1.3798]])


NOTE : 任何以'_' 结尾的操作，都会用结果替换原变量，例如``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``

In [11]:
print(x)
print(x[:,1]) # 第二列

tensor([[-0.6338, -1.6565, -0.9811],
        [-1.3722, -0.1331,  1.2598],
        [-0.7445,  0.2115,  0.0526],
        [-0.9367,  0.2224,  1.3718],
        [ 1.7385, -0.1596,  0.7639]])
tensor([-1.6565, -0.1331,  0.2115,  0.2224, -0.1596])


torch.view 可以改变张量的维度和大小  和 Numpy d reshape 类似

In [12]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) #确定列数，让 系统自己 确定 行数
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
#当 只有一个元素的 张量的 使用.item()来得到Python数据类型的数值
x = torch.tensor([1.0000001])
print(x)
print(x.item())# 注意⚠️！！！  元素为小数的时候不能准确显示，会有较大的误差

tensor([1.0000])
1.0000001192092896


### Numpy 转换
一个tensor 可以转换为 Numpy 反之亦然


tensor 和 numpy 共享底层内存地址，修改一个会导致另外一个的变化

In [14]:
# 将tensor 转换为 numpy 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
# 观察numpy数组的值是如何改变的 
a.add_(1)
print(a,"b",b)


tensor([2., 2., 2., 2., 2.]) b [2. 2. 2. 2. 2.]


numpy array 转换为 torch tensor

In [16]:
# 使用from_numpy自动转化 
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a) # 改变其中一个，两者都改变
print('a',a)
print('b',b)

a [2. 2. 2. 2. 2.]
b tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
torch.cuda.is_available()

False

In [18]:
torch.cuda.is_available() and torch.cuda.is_macos_available()

False

In [19]:
print(torch.__version__)

2.0.0


In [20]:

 
print(torch.backends.mps.is_available()) 
print(torch.backends.mps.is_built())

True
True


In [21]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [23]:
print(y.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()

print(z, 'out',out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) out tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_(...)是PyTorch中张量（Tensor）的一个方法，用于动态地更改张量的requires_grad属性。

当一个张量被创建时，可以使用requires_grad参数来指定是否需要计算该张量的梯度。但是，有时候需要动态地更改张量的requires_grad属性，例如在模型的训练过程中需要冻结部分参数。在这种情况下，就可以使用.requires_grad_(...)方法。


False 就是冻结梯度运算

In [25]:
a = torch.randn(2,2)
a = (a * 3) / (a - 1)
print(a.requires_grad)# 默认是false
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [26]:
out 

tensor(27., grad_fn=<MeanBackward0>)

### 梯度

可以通过调用y.backward()来计算y相对于所有需要梯度的张量的梯度。

如果需要将梯度存储到一个已经创建好的张量中，可以在backward()方法中指定一个out参数，该参数表示梯度将要被存储的张量 

In [27]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = torch.zeros(2, 2)
z.backward(out)
out

tensor([[0., 0.],
        [0., 0.]])

torch.autograd模块提供了自动求导的功能，可以自动计算张量的梯度。自动求导是通过记录张量的操作历史来实现的。每个张量都有一个requires_grad属性，用于指示是否需要计算该张量的梯度。如果一个张量的requires_grad属性为True，那么它将被认为是一个需要求导的节点，并且所有的操作都将被记录下来。

一旦所有的操作都完成了，可以调用backward()方法来计算所有需要梯度的张量的梯度。backward()方法会沿着操作历史反向传播梯度，并将梯度累加到每个张量的grad属性中。需要注意的是，对于同一个张量进行多次反向传播时，每次反向传播都会累加梯度到该张量的grad属性中。

In [28]:
x = torch.randn(3, requires_grad=True)
y = x * 2 
while y.data.norm() < 1000:
    y = y * 2
    pass
print(y)

tensor([ -32.8415, -967.9934,  395.6252], grad_fn=<MulBackward0>)


在这个情形中，y不再是个标量。torch.autograd无法直接计算出完整的雅可比行列，但是如果我们只想要vector-Jacobian product，只需将向量作为参数传入backward

需要注意的是，只有在标量上调用backward()函数才是有效的。如果y不是标量，那么可以使用gradient参数来指定一个张量，该张量与y具有相同的形状，用于计算y的梯度。在这种情况下，gradient张量中的每个元素都将乘以相应的y的梯度，然后求和，以得到一个标量，最后将该标量用于反向传播。

In [29]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [30]:


x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

# 获取排除梯度的张量数据
y_data = y.detach()
print(y_data)


tensor([[3., 3.],
        [3., 3.]])


In [31]:


# 创建一个张量
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]], requires_grad=True)

# 进行一些操作
y = x.pow(2).sum()
print(y)

# 计算梯度
y.backward()

# 输出梯度
print(x.grad)


tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [32]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]], requires_grad=True)

# 进行一些操作
y = x.pow(2)
print(y)

# 计算梯度
gradients = torch.tensor([[2,3,2],
                          [1,1,1]])
y.backward(gradients)

# 输出梯度
print(x.grad)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]], grad_fn=<PowBackward0>)
tensor([[ 4., 12., 12.],
        [ 8., 10., 12.]])


------------------------------------------------------

回顾autograd机制


------------------------------------------------------

In [34]:
x = torch.randn(3,4,requires_grad=True)
x

tensor([[-0.2552, -1.7295, -0.5089, -0.1170],
        [-2.4160,  1.3484, -0.2134,  1.9794],
        [ 0.1945, -0.9690,  0.1436,  1.3074]], requires_grad=True)