## question  
Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.Suppose the following input is supplied to the program:

In [5]:
list1=input('please input number:').split(',')# 逗号隔开，不会输出逗号
print(tuple(list1))
print(list(list1))


('1', '2', '3', '4', '5')
['1', '2', '3', '4', '5']


Define a class which has at least two methods:

getString: to get a string from console input


printString: to print the string in upper case.


Also please include simple test function to test the class methods.

In [6]:
# 复习类  
class animal():
    def __init__(self,name,colour):
        self.name=name
        self.colour=colour
        pass
    pass


In [7]:
dog=animal('wangcai','red')
print(dog.name)
print(dog.colour)

wangcai
red


In [17]:
# 做法
class Tosting():
    def getsrting(self):
        self.s=input()
    def printstring(self):
        print(self.s.swapcase())
        pass


In [21]:
x=Tosting()
x.getsrting()
x.printstring()

SDFSDFSD


In [20]:
# 直接输入 有单引号
a=input('input number:')
b=a.swapcase()
b

'ASDFDS'

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 _ C _ D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.For example Let us assume the following comma separated input sequence is given to the program:



In [26]:
from math import sqrt 

c=50
h=30
def cal(D):
    Q=sqrt((2*c*D)/h)
    return Q
    pass
D=[int(i) for i in input('number is :').split(',')]
D=[cal(i) for i in D]
D=[round(i) for i in D]
D=[str(i) for i in D]
print(','.join(D))


6,6,18


**_Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i _ j.***

Note: i=0,1.., X-1; j=0,1,¡­Y-1. Suppose the following inputs are given to the program: 3,5

Then, the output of the program should be:

In [54]:
#method 1 
import numpy as np
x,y=map(int,input('number is :').split(','))
tep=np.zeros([x,y])
for i in range(x):
    for j in range(y):
        tep[i,j]+=i*j
        pass
    pass
print(tep)

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]]


In [42]:
#测试
import numpy as np
zz=np.zeros([2,3])
zz[1,1]

0.0

In [52]:
# 失败的例子 得用map
xx=input().split(',')
print(xx)
xx(0)
xx(1)

['3', '4']


TypeError: 'list' object is not callable

In [55]:
#method 2 
x, y = map(int, input().split(","))
lst = []

for i in range(x):
    tmp = []
    for j in range(y):
        tmp.append(i * j)
    lst.append(tmp)

print(lst)

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]


Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world
# 要记得join

In [57]:
lis=input('pleace:').split(',')
lis.sort()
print(','.join(lis))

bag,hollo,without


Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

Suppose the following input is supplied to the program:

Hello world

Practice makes perfect

Then, the output should be:

HELLO WORLD

PRACTICE MAKES PERFECT

In [60]:
lis=input()
lis1=lis.upper()
print(lis1)


HELLO WORLD


## Question 10
### Question
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world

In [62]:
word=input().split(' ')
for i in word:
    if word.count(i)>1:
        word.remove(i)
        pass
    pass
word.sort()
print(' '.join(word))

 a b bc c ca g h


## Question 11
### Question
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:

0100,0011,1010,1001

Then the output should be:

1010



In [64]:
D=[int(i,2) for i in input('2 number:').split(',')]
A=[ ]
for i in D:
    if i%5==0:
        A.append(i)
        pass
    pass
B=[bin(i).replace('0b','') for i in A]# 去掉0b的前缀
print(','.join(B))


1010


## Question 12
### Question:
Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

Solutions:

In [70]:
lis=[ ]
for i in range(1000,3001):
    if i%2==0:
        lis.append(str(i))
        pass
    pass
print(type(lis))
print(','.join(lis))

<class 'list'>
1000,1002,1004,1006,1008,1010,1012,1014,1016,1018,1020,1022,1024,1026,1028,1030,1032,1034,1036,1038,1040,1042,1044,1046,1048,1050,1052,1054,1056,1058,1060,1062,1064,1066,1068,1070,1072,1074,1076,1078,1080,1082,1084,1086,1088,1090,1092,1094,1096,1098,1100,1102,1104,1106,1108,1110,1112,1114,1116,1118,1120,1122,1124,1126,1128,1130,1132,1134,1136,1138,1140,1142,1144,1146,1148,1150,1152,1154,1156,1158,1160,1162,1164,1166,1168,1170,1172,1174,1176,1178,1180,1182,1184,1186,1188,1190,1192,1194,1196,1198,1200,1202,1204,1206,1208,1210,1212,1214,1216,1218,1220,1222,1224,1226,1228,1230,1232,1234,1236,1238,1240,1242,1244,1246,1248,1250,1252,1254,1256,1258,1260,1262,1264,1266,1268,1270,1272,1274,1276,1278,1280,1282,1284,1286,1288,1290,1292,1294,1296,1298,1300,1302,1304,1306,1308,1310,1312,1314,1316,1318,1320,1322,1324,1326,1328,1330,1332,1334,1336,1338,1340,1342,1344,1346,1348,1350,1352,1354,1356,1358,1360,1362,1364,1366,1368,1370,1372,1374,1376,1378,1380,1382,1384,1386,1388,1390,1392,

## Question 13
### Question:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3

In [71]:
lis=input()
letter,digit=0,0
for i in lis:
    if i.isalpha():#    
        letter+=1
        pass
    if i.isdigit():
        digit+=1
        pass
    pass
print('LETTERS:{}\nDIGITS:{}'.format(letter,digit))

LETTERS:10
DIGITS:3


## Question 14
### Question:
Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.

Suppose the following input is supplied to the program:

Hello world!

Then, the output should be:

UPPER CASE 1

LOWER CASE 9

In [74]:
word=input()
low,upper=0,0
for i in word:
    if i.islower():#判断小写字母
        low+=1
        pass
    if i.isupper():
        upper+=1
        pass
    pass
print('UPPER CASE {}\nLOWVER CASE {}'.format(upper,low))

UPPER CASE 1
LOWVER CASE 9


In [73]:
lis=['J','M','k']
for i in lis:
    print(i.islower())
    pass


False
False
True


## Question 15
### Question:
Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.

Suppose the following input is supplied to the program:

9

Then, the output should be:

11106



In [76]:
a=input()
print(type(a))
b=int(a)+int(a*2)+int(a*3)+int(a*4)#重复字符串的操作方法
print(b)

<class 'str'>
11106


## Question 16
### Question:
Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers. >Suppose the following input is supplied to the program:

1,2,3,4,5,6,7,8,9

Then, the output should be:

1,9,25,49,81



In [84]:
lis=input().split(',')
lis1=[ ]
for i in lis:
    if int(i)%2==1:
        lis1.append(int(i)**2)
        pass
    pass
lis1=[str(i) for i in lis1]
print(','.join(lis1))

1,9,25


## Question 17
### Question:
Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:

D 100

W 200

D means deposit while W means withdrawal.
     Suppose the following input is supplied to the program:

D 300

D 300

W 200

D 100

  Then, the output should be:

500

In [3]:
account = 0
while True:
    action = input("Deposit/Whitdrow/Balance/Quit? D/W/B/Q: ").lower()
    if action == "d":
        deposit = input("How much would you like to deposit? ")
        account = account + int(deposit)
    elif action == "w":
        withdrow = input("How much would you like to withdrow? ")
        account = account - int(withdrow)
    elif action == "b":
        print(account)
    else:
        quit()

0
2000
2000
2000


## Quesstion19
You are required to write a program to sort the (name, age, score) tuples by ascending order where name is string, age and score are numbers. The tuples are input by console. The sort criteria is:

1: Sort based on name
2: Then sort based on age
3: Then sort by score
The priority is that name > age > score.

If the following tuples are given as input to the program:

### 如何根据 不同的类别排序

In [10]:
llis=[ ]
while True:
    a=input().split(',')#数组
    if not a[0]:
        break
    llis.append(a)
    pass
print(llis[0][1])#数组可以嵌套
llis.sort(key=lambda x:(x[0],x[1],x[2]))#调整排序的优先类别
print(llis)

19
[['John', '20', '90'], ['Jony', '17', '91'], ['Jony', '17', '93'], ['Json', '21', '85'], ['Tom', '19', '80']]


## Question 20
### Question:
Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

Hints:
Consider use class, function and comprehension.